/*

    IMPORTANT! This file is auto-generated by the Jucer each time you save your
    project - if you alter its contents, your changes may be overwritten!

    If you want to change any of these values, use the Jucer to do so, rather than
    editing this file directly!

    Any commented-out settings will fall back to using the default values that
    they are given in juce_Config.h

*/

//#define  JUCE_FORCE_DEBUG
//#define  JUCE_LOG_ASSERTIONS
//#define  JUCE_ASIO
//#define  JUCE_WASAPI
//#define  JUCE_DIRECTSOUND
//#define  JUCE_ALSA
#define    JUCE_QUICKTIME 0
#define    JUCE_OPENGL 0
#define    JUCE_DIRECT2D 0
#define    JUCE_USE_FLAC 0
#define    JUCE_USE_OGGVORBIS 0
#define    JUCE_USE_CDBURNER 0
#define    JUCE_USE_CDREADER 0
#define    JUCE_USE_CAMERA 0
#define    JUCE_ENABLE_REPAINT_DEBUGGING 0
#define    JUCE_USE_XINERAMA 0
#define    JUCE_USE_XSHM 0
#define    JUCE_USE_XRENDER 0
#define    JUCE_USE_XCURSOR 0
#define    JUCE_PLUGINHOST_VST 0
#define    JUCE_PLUGINHOST_AU 0
//#define  JUCE_ONLY_BUILD_CORE_LIBRARY
#define    JUCE_WEB_BROWSER 0
#define    JUCE_SUPPORT_CARBON 0
//#define  JUCE_CHECK_MEMORY_LEAKS
//#define  JUCE_CATCH_UNHANDLED_EXCEPTIONS
