/*

    IMPORTANT! This file is auto-generated by the Jucer each time you save your
    project - if you alter its contents, your changes may be overwritten!

    This is the header file that your files should include in order to get all the
    Juce library headers. You should NOT include juce.h or juce_amalgamated.h directly in
    your own source files, because that wouldn't pick up the correct Juce configuration
    options for your app.

*/

#ifndef __APPHEADERFILE_240CB505__
#define __APPHEADERFILE_240CB505__

#include "AppConfig.h"
#if defined (JUCER_VS2010_78A501D)
 #include "../../juce/juce_amalgamated.h"
#elif defined (JUCER_VS2008_78A5006)
 #include "../../../juce_source/juce/juce_amalgamated.h"
#elif defined (JUCER_VS2005_78A5003)
 #include "../../../juce_source/juce/juce_amalgamated.h"
#elif defined (JUCER_MSVC6_734A9119)
 #include "../../../juce_source/juce/juce_amalgamated.h"
#elif defined (JUCER_XCODE_IPHONE_5BC26AE3)
 #include "../../../juce_source/juce/juce_amalgamated.h"
#elif defined (JUCER_XCODE_MAC_F6D2F4CF)
 #include "../../../../juce_source/juce/juce_amalgamated.h"
#endif

namespace ProjectInfo
{
    const char* const  projectName    = "Network Audio Streamer";
    const char* const  versionString  = "1.0.0";
    const int          versionNumber  = 0x10000;
}

#endif   // __APPHEADERFILE_240CB505__
