/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_F74EDC4B__
#define __PLUGINEDITOR_H_F74EDC4B__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "TremoloLookAndFeel.h"
#include "TremoloBufferView.h"


//==============================================================================
/**
*/
class TremoloAudioProcessorEditor : public AudioProcessorEditor,
                                    public Value::Listener,
                                    public Slider::Listener
{
public:
    TremoloAudioProcessorEditor (TremoloAudioProcessor* ownerFilter);
    ~TremoloAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics& g);
    
    void resized();
    
    void valueChanged (Value& value);
    
    void sliderValueChanged (Slider* slider);
    
    void sliderDragStarted (Slider* slider);
    
    void sliderDragEnded (Slider* slider);
    
private:
    
    //==============================================================================
    ScopedPointer<PluginLookAndFeel> customLookAndFeel;

    OwnedArray<Slider> sliders;
    OwnedArray<Label> labels;
			
	ScopedPointer<TremoloBufferView> bufferViewL;
	ScopedPointer<TremoloBufferView> bufferViewR;
	
	ScopedPointer<Label> bufferViewLLabel;
    ScopedPointer<Label> bufferViewRLabel;

};


#endif  // __PLUGINEDITOR_H_F74EDC4B__
