/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINPROCESSOR_H_CC1BF768__
#define __PLUGINPROCESSOR_H_CC1BF768__

#include "../JuceLibraryCode/JuceHeader.h"


//==============================================================================
/**
*/
class TremoloAudioProcessor :   public AudioProcessor,
                                public Value::Listener
{
public:
    //==============================================================================
    TremoloAudioProcessor();
    ~TremoloAudioProcessor();

    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock);
    void releaseResources();

    void processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages);

    //==============================================================================
    AudioProcessorEditor* createEditor();
    bool hasEditor() const;

    //==============================================================================
    const String getName() const;

    int getNumParameters();

    float getParameter (int index);
    void setParameter (int index, float newValue);

    float getScaledParameter (int parameterIndex);
    void setScaledParameter (int parameterIndex, float newValue);
	float getParameterMin (int parameterIndex);
    float getParameterMax (int parameterIndex);
    float getParameterDefault (int parameterIndex);
    //==============================================================================

    const String getParameterName (int index);
    const String getParameterText (int index);

    const String getInputChannelName (int channelIndex) const;
    const String getOutputChannelName (int channelIndex) const;
    bool isInputChannelStereoPair (int index) const;
    bool isOutputChannelStereoPair (int index) const;

    bool acceptsMidi() const;
    bool producesMidi() const;

    //==============================================================================
    int getNumPrograms();
    int getCurrentProgram();
    void setCurrentProgram (int index);
    const String getProgramName (int index);
    void changeProgramName (int index, const String& newName);

    //==============================================================================
    void getStateInformation (MemoryBlock& destData);
    void setStateInformation (const void* data, int sizeInBytes);

    //==============================================================================
    void valueChanged (Value& value);
    
    //==============================================================================    
    PluginParameter& getPluginParameter (int index);
    
    float* getTremoloBuffer (int bufferIndex);
    int getTremoloBufferSize()                  {   return tremoloBufferSize;   }
    
    enum Paramemeters
    {
        rateParam = 0,
        depthParam,
        shapeParam,
        phaseParam,
        
        totalNumParams
    };
    
private:
    
    Array<PluginParameter> parameters;
    
    double currentSampleRate;
    double tremoloBufferPosition;
    double tremoloBufferIncriment;
    
    const int tremoloBufferSize;
	HeapBlock<float> tremoloBufferL;
	HeapBlock<float> tremoloBufferR;

    void fillBuffer(float* bufferToFill, float phaseAngleRadians);

    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (TremoloAudioProcessor);
};

#endif  // __PLUGINPROCESSOR_H_CC1BF768__
