/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_5D3F4861__
#define __PLUGINEDITOR_H_5D3F4861__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class FdnreverbAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    FdnreverbAudioProcessorEditor (FdnreverbAudioProcessor* ownerFilter);
    ~FdnreverbAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
};


#endif  // __PLUGINEDITOR_H_5D3F4861__
