/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINPROCESSOR_H_914E0B92__
#define __PLUGINPROCESSOR_H_914E0B92__

#include "../JuceLibraryCode/JuceHeader.h"

#include "FDNReverb/FDNReverb.h"
#include "FDNReverb/MultitapDelayLine.h"

//==============================================================================
/**
*/
class FdnreverbAudioProcessor  : public AudioProcessor
{
public:
    //==============================================================================
    FdnreverbAudioProcessor();
    ~FdnreverbAudioProcessor();

    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock);
    void releaseResources();

    void processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages);

    //==============================================================================
    AudioProcessorEditor* createEditor();
    bool hasEditor() const;

    //==============================================================================
    const String getName() const;

    int getNumParameters();

    float getParameter (int index);
    void setParameter (int index, float newValue);

    const String getParameterName (int index);
    const String getParameterText (int index);

    const String getInputChannelName (int channelIndex) const;
    const String getOutputChannelName (int channelIndex) const;
    bool isInputChannelStereoPair (int index) const;
    bool isOutputChannelStereoPair (int index) const;

    bool acceptsMidi() const;
    bool producesMidi() const;

    //==============================================================================
    int getNumPrograms();
    int getCurrentProgram();
    void setCurrentProgram (int index);
    const String getProgramName (int index);
    void changeProgramName (int index, const String& newName);

    //==============================================================================
    void getStateInformation (MemoryBlock& destData);
    void setStateInformation (const void* data, int sizeInBytes);

private:
    //==============================================================================
    Array<PluginParameter> parameters;
    
    enum { numChannels = 2 };

    FDNReverb reverb;
    //MultitapDelayLine delay[numChannels];
    
    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (FdnreverbAudioProcessor);
};

#endif  // __PLUGINPROCESSOR_H_914E0B92__
